### ISSUE TITLE
Not working on IE11 due to the use of arrow function

### ISSUE THREAD

**Issue by pmrotule** [sindresorhus/escape-string-regexp#24] opened 2020-04-24 15:48 UTC
I started using this module in the frontend using Webpack then I realized it was breaking my app on IE11 because it uses an arrow function which is not supported. Would be great to change it for a normal function to have a wider range of supported browsers. Thanks!

**Comment by sindresorhus** [comment] 2020-04-24 16:07
Duplicate of #18

**Closed by sindresorhus** 2020-04-24 16:07 UTC
